-- Add notification preferences and OneSignal player id to profiles
ALTER TABLE IF EXISTS "profiles"
ADD COLUMN IF NOT EXISTS notification_prefs jsonb DEFAULT '{}'::jsonb;

ALTER TABLE IF EXISTS "profiles"
ADD COLUMN IF NOT EXISTS one_signal_player_id text;

-- Backfill: set default prefs to enable browser notifications for existing profiles
UPDATE "profiles"
SET notification_prefs = jsonb_set(COALESCE(notification_prefs, '{}'::jsonb), '{browser_notifications_enabled}', 'true'::jsonb)
WHERE notification_prefs IS NULL OR notification_prefs = '{}'::jsonb;

-- Index for quick lookup by player id
CREATE INDEX IF NOT EXISTS idx_profiles_one_signal_player_id ON "profiles" (one_signal_player_id);

-- Create blocks table
CREATE TABLE blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id UUID REFERENCES users (id) ON DELETE CASCADE,
    blocked_user_id UUID REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Add RLS policy for memories table to exclude blocked users
ALTER TABLE memories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Exclude blocked users"
ON memories
FOR SELECT
USING (
    NOT EXISTS (
        SELECT 1 FROM blocks
        WHERE blocks.blocker_id = auth.uid()
        AND blocks.blocked_user_id = memories.user_id
    )
);

-- Create reports table
CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID REFERENCES users (id) ON DELETE CASCADE,
    reported_user_id UUID REFERENCES users (id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
